function taskRow(task: Record<string, unknown>, long: boolean, color: boolean) { const due = typeof task.deadline === "string" ? task.deadline : "INBOX"; const rawPriority = typeof task.priority === "string" ? task.priority.toUpperCase() : "—"; const priority = color && rawPriority === "P1" ? `\x1b[31m${rawPriority}\x1b[0m` : rawPriority; const title = String(task.title ?? "Untitled"); const compact = `${due.padEnd(10)} ${priority}${" ".repeat(Math.max(0, 3 - rawPriority.length))} ${title}`; if (!long) return compact; const goal = task.goal && typeof task.goal === "object" ? (task.goal as Record<string, unknown>).text ?? (task.goal as Record<string, unknown>).title : null; const details = [goal && `goal ${goal}`, task.time && `time ${task.time}`, typeof task.estimatedMinutes === "number" && `${task.estimatedMinutes} min`, Array.isArray(task.tags) && task.tags.length ? `tags ${task.tags.join(", ")}` : null, task.description && String(task.description), `id ${task.id}`].filter(Boolean).join(" · "); return `${compact}\n  ${details}`; }
function taskList(tasks: unknown, long: boolean, color: boolean) { const rows = Array.isArray(tasks) ? tasks.map((task) => taskRow(task as Record<string, unknown>, long, color)) : []; return rows.length ? ["DUE        PRI TASK", ...rows].join("\n") : "No Tasks."; }
export function renderHumanResult(command: string, data: unknown, long: boolean, color = false) {
  const value = data as Record<string, unknown>;
  if (command === "tasks list" && "overdue" in value) return ["Overdue", taskList(value.overdue, long, color), "", "Today", taskList(value.todayTasks, long, color), "", "Upcoming", taskList(value.upcoming, long, color), "", `Inbox: ${value.inboxCount ?? 0}`].join("\n");
  if (["inbox", "today", "overdue", "upcoming"].includes(command) || command === "tasks list") return taskList(value.tasks, long, color);
  if (command === "tasks show") return taskList([value.task], true, color);
  if (command === "goals list") return Array.isArray(value.goals) && value.goals.length ? ["DUE        PRI GOAL  PROGRESS", ...value.goals.flatMap((goal) => { const g = goal as Record<string, unknown>; const progress = g.progress as Record<string, unknown> | undefined; const row = `${String(g.deadline ?? "—").padEnd(10)} ${String(g.priority ?? "—").toUpperCase().padEnd(3)} ${String(g.text)}  ${progress ? `${progress.completed}/${progress.active}` : "0/0"}`; return long ? [row, `  ${[g.description && String(g.description), `id ${g.id}`].filter(Boolean).join(" · ")}`] : [row]; })].join("\n") : "No Goals.";
  if (command === "goals show") { if (!value.goal || typeof value.goal !== "object") return "No Goal."; const goal = value.goal as Record<string, unknown>; return `${goal.text}\nProgress: ${(goal.progress as Record<string, unknown>)?.completed ?? 0}/${(goal.progress as Record<string, unknown>)?.active ?? 0}\nHistorical: ${goal.historicalTaskCount ?? 0}\n${taskList(goal.activeTasks, long, color)}`; }
  if (command === "doctor") return Array.isArray(value.checks) ? value.checks.map((check) => { const c = check as Record<string, unknown>; return `${c.ok ? "OK" : "FAIL"} ${c.name}: ${c.ok ? "ready" : c.remedy}`; }).join("\n") : "Doctor unavailable.";
  if (value.action && value.target) { const target = value.target as Record<string, unknown>; const operation = value.operation as Record<string, unknown> | undefined; return [`${value.action}: ${target.title ?? target.id}`, operation?.undoAvailable && operation.operationId ? `Undo: pravah operations undo ${operation.operationId}` : null, operation?.undoExpiresAt ? `Expires: ${operation.undoExpiresAt}` : null].filter(Boolean).join("\n"); }
  if (command === "auth login") return `Authenticated as ${value.credentialLabel ?? "credential"}\nEndpoint: ${value.siteUrl ?? "configured default"}\nScopes: ${Array.isArray(value.scopes) ? value.scopes.join(", ") : "none"}`;
  if (command === "auth status") return value.authenticated ? `Authenticated as ${value.credentialLabel}\nEndpoint: ${value.siteUrl}\nScopes: ${Array.isArray(value.scopes) ? value.scopes.join(", ") : "none"}` : "Not authenticated. Run `pravah auth login`.";
  if (command === "auth logout") return "Local credential removed.";
  if (command === "operations list") return Array.isArray(value.operations) && value.operations.length ? value.operations.map((operation) => { const op = operation as Record<string, unknown>; return `${op.operationId}  ${op.operation}  ${op.targetId ?? "—"}  ${op.status ?? "—"}  ${op.undoAvailable ? `Undo until ${op.undoExpiresAt ?? "expiry unavailable"}` : "Not undoable"}`; }).join("\n") : "No operations.";
  if (command === "agent context") return "Agent context is machine-oriented; use --json.";
  return "Done.";
}
